# Generated by Django 2.0.2 on 2018-06-26 06:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180626_0609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 26, 6, 10, 4, 895018, tzinfo=utc)),
        ),
    ]
