# Generated by Django 2.0.2 on 2018-07-02 18:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180702_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 2, 18, 54, 43, 422122, tzinfo=utc)),
        ),
    ]
